### PR TITLE
added the link to second lecture in README

### LINKED ISSUE #2: Second link isnt going through
The link for the second virtual lecture in the README is displaying 404.

### PR DESCRIPTION
**Pull request by OgunmisiM**
This PR if merged fixes #2

### CODE REVIEW

**Review by OSCA-Ado-Ekiti — CHANGES_REQUESTED** [review]
Adding this alone fixes it.

"Git-and-Github-as-an-Open-Source-Tool.md"

Can you apply this changes, thanks for contributing.

**Review by OSCA-Ado-Ekiti — APPROVED** [review]

**Comment by OSCA-Ado-Ekiti** [comment]
> This PR if merged fixes #2

I have applied the changes myself, thanks for contributing, also please note next time, the best practices to sending a pull request should be from another branch and not the main branch.

Thanks once again

**Comment by OgunmisiM** [comment]
From another branch, how?

**Comment by OSCA-Ado-Ekiti** [comment]
We've discussed That on Friday, but here is a guide too:
https://www.google.com/amp/s/www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/amp/

**Pull request merged**
